package com.conservation.model;

/**
 * Assistant Keeper - junior staff member with basic care responsibilities.
 * 
 * Assistant keepers are responsible for:
 * - Daily animal care (feeding, cleaning)
 * - Monitoring animal health
 * - Reporting issues to head keepers
 * - Following instructions from senior staff
 * 
 * Assistant keepers do NOT have authority to allocate animals or keepers to cages.
 * 
 * Extends the abstract Keeper class with assistant-specific behaviour.
 */
public class AssistantKeeper extends Keeper {
    
    private int supervisorId;  // ID of the Head Keeper supervising this assistant
    
    /**
     * Default constructor for creating empty AssistantKeeper instance.
     * Required for XML deserialisation.
     */
    public AssistantKeeper() {
        super();
        this.position = Position.ASSISTANT_KEEPER;
    }
    
    /**
     * Full constructor for creating an AssistantKeeper with all attributes.
     * 
     * Automatically sets position to ASSISTANT_KEEPER.
     * 
     * @param keeperId unique identifier (auto-generated by system)
     * @param firstName keeper's first name
     * @param surname keeper's surname
     * @param address keeper's residential address
     * @param contactNumber keeper's phone number
     */
    public AssistantKeeper(int keeperId, String firstName, String surname,
                          String address, String contactNumber) {
        super(keeperId, firstName, surname, address, contactNumber, Position.ASSISTANT_KEEPER);
    }
    
    /**
     * Gets the responsibilities specific to an Assistant Keeper.
     * 
     * @return description of assistant keeper responsibilities
     */
    @Override
    public String getResponsibilities() {
        return "Daily animal care, health monitoring, and reporting to head keepers. " +
               "No allocation or management responsibilities.";
    }
    
    /**
     * Assistant keepers do not have management permissions.
     * 
     * @return false - assistant keepers cannot make management decisions
     */
    @Override
    public boolean hasManagementPermissions() {
        return false;
    }
    
    /**
     * Reports an issue to the supervising head keeper.
     * 
     * Assistant keepers must report problems rather than making decisions independently.
     * 
     * @param issueDescription description of the issue to report
     * @return confirmation message
     */
    public String reportIssue(String issueDescription) {
        return String.format("Assistant Keeper %s reported issue: %s",
                           getFullName(), issueDescription);
    }
    
    /**
     * Performs daily care routine for assigned cages.
     * 
     * Includes feeding, cleaning, and health checks.
     * 
     * @param cageId the cage to perform care routine for
     * @return status message
     */
    public String performDailyCare(int cageId) {
        if (!getAllocatedCageIds().contains(cageId)) {
            return String.format("Error: Cage %d is not allocated to %s", 
                               cageId, getFullName());
        }
        return String.format("Assistant Keeper %s completed daily care for Cage %d",
                           getFullName(), cageId);
    }
    
    /**
     * Gets the ID of the head keeper supervising this assistant.
     * 
     * @return supervisor's keeper ID, or 0 if not assigned
     */
    public int getSupervisorId() {
        return supervisorId;
    }
    
    /**
     * Sets the supervising head keeper for this assistant.
     * 
     * @param supervisorId the keeper ID of the supervising head keeper
     */
    public void setSupervisorId(int supervisorId) {
        this.supervisorId = supervisorId;
    }
    
    @Override
    public String toString() {
        return String.format("AssistantKeeper{id=%d, name='%s', cages=%d/%d, supervisor=%d}",
                keeperId, getFullName(), getAllocatedCageCount(), 4, supervisorId);
    }
}
